/**
 * Career catalog — general, country-neutral guidance. Education paths vary
 * by country; pages say so rather than pretending one path fits everyone.
 * No salary figures or "best career" rankings on purpose.
 */

export const CAREER_CATEGORIES = [
  "Software Engineering",
  "AI/ML",
  "Data",
  "Cybersecurity",
  "Cloud",
  "Product",
  "Design",
  "Finance",
  "Healthcare",
  "Medicine",
  "Law",
  "Business",
  "Marketing",
  "Sales",
  "Research",
  "Engineering",
  "Government",
  "Entrepreneurship",
  "Creative",
] as const;
export type CareerCategory = (typeof CAREER_CATEGORIES)[number];

export interface RoadmapStep {
  key: string;
  title: string;
  detail: string;
}

export interface Career {
  slug: string;
  title: string;
  category: CareerCategory;
  summary: string;
  overview: string;
  education: string[];
  skills: string[];
  tools: string[];
  responsibilities: string[];
  roadmap: RoadmapStep[];
  advanced: string[];
  projects: { level: "beginner" | "intermediate" | "advanced"; title: string; brief: string }[];
  interviewTopics: string[];
  resumeTips: string[];
  resources: { title: string; url: string }[];
  related: string[];
  /** Rough entry path: "degree" typically needs a formal degree/licence; "skills" can be entered via demonstrable skills. */
  entry: "degree" | "skills" | "either";
}

const s = (key: string, title: string, detail: string): RoadmapStep => ({ key, title, detail });

export const careers: Career[] = [
  {
    slug: "software-engineer",
    title: "Software Engineer",
    category: "Software Engineering",
    entry: "either",
    summary: "Design, build, test and maintain software systems that people and businesses rely on.",
    overview:
      "Software engineers turn requirements into working, maintainable code. Day to day that means writing features, reviewing teammates' code, fixing bugs, and thinking about how a system behaves under real load. Strong engineers are as good at communication and trade-offs as they are at syntax.",
    education: [
      "A degree in computer science or a related field is common but not required everywhere.",
      "Many engineers enter through self-study, bootcamps or apprenticeships backed by a strong project portfolio.",
    ],
    skills: ["One language in depth (e.g. TypeScript, Python, Java, Go)", "Data structures & algorithms", "Git & code review", "Testing", "APIs & HTTP", "SQL & data modelling", "System design basics", "Debugging"],
    tools: ["Git & GitHub", "VS Code or JetBrains IDEs", "Docker", "CI/CD (e.g. GitHub Actions)", "PostgreSQL", "Cloud platforms"],
    responsibilities: ["Implement features from specs", "Write and maintain automated tests", "Review code and give feedback", "Debug production issues", "Collaborate with product and design", "Document decisions"],
    roadmap: [
      s("lang", "Learn one language well", "Variables, control flow, functions, collections, error handling, modules."),
      s("git", "Git & collaboration", "Branches, pull requests, resolving conflicts, writing good commit messages."),
      s("dsa", "Data structures & algorithms", "Arrays, hash maps, stacks, queues, trees, graphs, Big-O, recursion."),
      s("web", "How the web works", "HTTP, REST, JSON, authentication basics."),
      s("db", "Databases", "SQL, joins, indexes, schema design, transactions."),
      s("testing", "Testing", "Unit, integration and end-to-end tests; test-driven habits."),
      s("project", "Build 2–3 real projects", "Deployed, documented, with tests and a clear README."),
      s("design", "System design fundamentals", "Caching, queues, scaling reads/writes, trade-offs."),
      s("interview", "Interview preparation", "Coding practice, behavioural stories, system design walkthroughs."),
    ],
    advanced: ["Distributed systems", "Performance profiling", "Security engineering", "Mentoring and technical leadership", "Architecture decision records"],
    projects: [
      { level: "beginner", title: "Personal task manager", brief: "CRUD app with authentication and a database." },
      { level: "intermediate", title: "URL shortener with analytics", brief: "API, rate limiting, click tracking, dashboards." },
      { level: "advanced", title: "Real-time collaborative editor", brief: "WebSockets, conflict resolution, presence, persistence." },
    ],
    interviewTopics: ["Arrays & strings", "Hash maps", "Trees & graphs", "Dynamic programming basics", "REST API design", "Database indexing", "Designing a scalable service", "Behavioural: conflict, ownership, failure"],
    resumeTips: ["Lead each bullet with impact, then how you did it.", "Link deployed projects and repositories.", "List technologies you can discuss in depth, not everything you've touched."],
    resources: [
      { title: "MDN Web Docs", url: "https://developer.mozilla.org/" },
      { title: "The Missing Semester (MIT)", url: "https://missing.csail.mit.edu/" },
      { title: "roadmap.sh", url: "https://roadmap.sh/" },
    ],
    related: ["frontend-developer", "cloud-engineer", "ai-engineer"],
  },
  {
    slug: "frontend-developer",
    title: "Frontend Developer",
    category: "Software Engineering",
    entry: "skills",
    summary: "Build the interfaces people see and use — fast, accessible and delightful on every device.",
    overview:
      "Frontend developers build the part of a product that users interact with. The job blends engineering with design sense: component architecture, state management, performance, accessibility and responsive layouts across phones, tablets and desktops.",
    education: ["No specific degree required; a strong portfolio of shipped interfaces matters most.", "Computer science or design backgrounds both work well."],
    skills: ["HTML semantics", "Modern CSS (flexbox, grid, responsive design)", "JavaScript & TypeScript", "A framework (React, Vue, Svelte or Angular)", "Accessibility (WCAG)", "Web performance", "Testing UI"],
    tools: ["React / Next.js", "Tailwind CSS", "Browser DevTools", "Vite", "Playwright or Cypress", "Figma"],
    responsibilities: ["Translate designs into components", "Manage client state and data fetching", "Ensure accessibility and responsiveness", "Optimise load performance", "Write UI tests"],
    roadmap: [
      s("html", "HTML & accessibility", "Semantic elements, forms, ARIA only when needed, keyboard navigation."),
      s("css", "CSS & responsive layout", "Box model, flexbox, grid, media queries, design tokens."),
      s("js", "JavaScript", "DOM, events, async/await, fetch, modules."),
      s("ts", "TypeScript", "Types, generics, narrowing, typing components."),
      s("framework", "A UI framework", "Components, props, state, effects, routing."),
      s("data", "Data fetching & state", "Server vs client state, caching, forms and validation."),
      s("perf", "Performance", "Core Web Vitals, code splitting, image optimisation."),
      s("testing", "Testing", "Component tests and end-to-end tests."),
      s("portfolio", "Portfolio", "Three polished, deployed projects with case-study write-ups."),
    ],
    advanced: ["Design systems", "Micro-frontends", "Animation & motion design", "Rendering strategies (SSR, SSG, streaming)", "PWA & offline"],
    projects: [
      { level: "beginner", title: "Responsive portfolio site", brief: "Accessible, fast, works beautifully on mobile." },
      { level: "intermediate", title: "Recipe finder", brief: "Search, filters, favourites, API integration, loading and empty states." },
      { level: "advanced", title: "Component library", brief: "Documented, themed, accessible components published as a package." },
    ],
    interviewTopics: ["Event loop", "Closures", "CSS layout", "React rendering & hooks", "Accessibility", "Web performance", "Build a UI component live"],
    resumeTips: ["Show before/after performance or accessibility improvements you actually measured.", "Link live demos — reviewers will click them."],
    resources: [
      { title: "MDN: Learn web development", url: "https://developer.mozilla.org/en-US/docs/Learn" },
      { title: "web.dev", url: "https://web.dev/" },
      { title: "React docs", url: "https://react.dev/" },
    ],
    related: ["software-engineer", "ux-designer"],
  },
  {
    slug: "ai-engineer",
    title: "AI Engineer",
    category: "AI/ML",
    entry: "either",
    summary: "Build reliable products on top of machine learning and large language models.",
    overview:
      "AI engineers integrate models into real software: retrieval-augmented generation, agents, evaluation, guardrails and cost/latency trade-offs. It's software engineering first, with enough ML understanding to know when a model is — and isn't — the right tool.",
    education: ["Computer science, data science or engineering degrees are common.", "Strong software engineers frequently move into AI engineering through projects."],
    skills: ["Python", "APIs", "SQL", "ML fundamentals", "LLM prompting & context design", "Retrieval (RAG) & embeddings", "Evaluation", "Agents & tool use", "Cloud deployment"],
    tools: ["Python", "Model provider APIs (Anthropic, OpenAI, Google)", "Vector databases / pgvector", "Docker", "Cloud platforms", "Evaluation frameworks"],
    responsibilities: ["Design AI features end to end", "Build retrieval pipelines", "Write evaluations and monitor quality", "Control cost, latency and safety", "Ship and iterate in production"],
    roadmap: [
      s("python", "Python", "Syntax, packaging, virtual environments, typing."),
      s("git", "Git", "Branching, pull requests, reviews."),
      s("apis", "APIs", "HTTP, REST, auth, rate limits, streaming responses."),
      s("sql", "SQL", "Querying, joins, indexes, Postgres."),
      s("ml", "Machine learning basics", "Supervised learning, evaluation metrics, overfitting."),
      s("llms", "LLMs", "Tokens, context windows, prompting, structured outputs."),
      s("rag", "Retrieval (RAG)", "Chunking, embeddings, vector search, citations."),
      s("agents", "Agents & tools", "Tool calling, planning, MCP concepts, guardrails."),
      s("cloud", "Cloud", "Deploying services, secrets, queues, observability."),
      s("prod", "Production AI", "Evals, monitoring, cost control, safety, fallbacks."),
      s("portfolio", "Portfolio", "Two deployed AI apps with evaluation write-ups."),
      s("interview", "Interview preparation", "System design for AI features, coding, trade-off discussions."),
    ],
    advanced: ["Fine-tuning", "Model evaluation at scale", "Multi-agent systems", "On-device inference", "AI security (prompt injection defence)"],
    projects: [
      { level: "beginner", title: "Study-notes Q&A bot", brief: "Answer questions over your own notes with citations." },
      { level: "intermediate", title: "Support agent with tools", brief: "Agent that looks up orders via tools, with an evaluation set." },
      { level: "advanced", title: "Evaluated RAG service", brief: "Hybrid search, reranking, regression evals and cost dashboards." },
    ],
    interviewTopics: ["RAG design", "Embeddings", "Evaluating LLM output", "Prompt injection", "Latency & cost trade-offs", "Python coding", "Designing an AI feature end to end"],
    resumeTips: ["Show how you evaluated quality, not just that you called an API.", "Mention real constraints you handled: latency, cost, safety."],
    resources: [
      { title: "Anthropic documentation", url: "https://docs.claude.com/" },
      { title: "Kaggle Learn", url: "https://www.kaggle.com/learn" },
      { title: "Model Context Protocol", url: "https://modelcontextprotocol.io/" },
    ],
    related: ["software-engineer", "data-analyst", "research-scientist"],
  },
  {
    slug: "data-analyst",
    title: "Data Analyst",
    category: "Data",
    entry: "skills",
    summary: "Turn raw data into clear answers that help teams make better decisions.",
    overview:
      "Data analysts clean, query and visualise data, then explain what it means. The most valuable analysts ask sharp questions, are careful about data quality, and communicate findings simply to non-technical people.",
    education: ["Degrees in statistics, economics, maths, business or computing are common.", "Many analysts enter via certificates and portfolio projects."],
    skills: ["SQL", "Spreadsheets", "Statistics fundamentals", "Data cleaning", "Visualisation", "Python or R", "Storytelling with data"],
    tools: ["SQL databases", "Excel / Google Sheets", "Power BI or Tableau", "Python (pandas)", "Jupyter"],
    responsibilities: ["Write queries to answer business questions", "Build and maintain dashboards", "Check data quality", "Present findings and recommendations"],
    roadmap: [
      s("sheets", "Spreadsheets", "Formulas, pivot tables, lookups, charts."),
      s("sql", "SQL", "SELECT, joins, GROUP BY, window functions."),
      s("stats", "Statistics", "Distributions, sampling, hypothesis tests, correlation vs causation."),
      s("viz", "Visualisation", "Choosing the right chart, dashboard design."),
      s("python", "Python for data", "pandas, cleaning, basic plotting."),
      s("story", "Communicating insight", "Writing clear summaries and recommendations."),
      s("portfolio", "Portfolio", "Three analyses on public datasets with written conclusions."),
    ],
    advanced: ["Experiment design (A/B testing)", "Data modelling (dbt)", "Forecasting", "Analytics engineering"],
    projects: [
      { level: "beginner", title: "Personal expense analysis", brief: "Clean a spending export and chart where money goes." },
      { level: "intermediate", title: "Public dataset dashboard", brief: "Interactive dashboard with a written insight report." },
      { level: "advanced", title: "A/B test analysis", brief: "Design and analyse an experiment with confidence intervals." },
    ],
    interviewTopics: ["SQL joins & window functions", "Metric definitions", "Case: why did a metric drop?", "Statistics basics", "Presenting to stakeholders"],
    resumeTips: ["Describe the decision your analysis informed.", "Name the datasets and tools you used."],
    resources: [
      { title: "Kaggle Learn", url: "https://www.kaggle.com/learn" },
      { title: "Khan Academy: Statistics", url: "https://www.khanacademy.org/math/statistics-probability" },
    ],
    related: ["ai-engineer", "business-analyst", "financial-analyst"],
  },
  {
    slug: "cybersecurity-analyst",
    title: "Cybersecurity Analyst",
    category: "Cybersecurity",
    entry: "either",
    summary: "Protect systems and data by detecting, investigating and preventing attacks.",
    overview:
      "Security analysts monitor systems for threats, investigate incidents, and help teams fix weaknesses. It rewards curiosity, patience and a methodical mindset, and it's a field where ethics and legal boundaries matter enormously.",
    education: ["Degrees in computing or security are common; recognised certifications are widely valued.", "IT support or networking experience is a frequent entry route."],
    skills: ["Networking (TCP/IP, DNS)", "Operating systems (Linux, Windows)", "Security fundamentals", "Log analysis", "Incident response", "Scripting (Python, Bash)", "Risk assessment"],
    tools: ["SIEM platforms", "Wireshark", "Nmap (on systems you're authorised to test)", "Linux command line", "Cloud security consoles"],
    responsibilities: ["Monitor alerts", "Investigate suspicious activity", "Respond to incidents", "Recommend and verify fixes", "Support security awareness"],
    roadmap: [
      s("net", "Networking", "OSI model, TCP/IP, DNS, HTTP, subnets."),
      s("os", "Operating systems", "Linux and Windows administration basics."),
      s("fundamentals", "Security fundamentals", "CIA triad, authentication, encryption, common vulnerabilities."),
      s("owasp", "Web security", "OWASP Top 10 and how to prevent each."),
      s("logs", "Detection & logs", "Reading logs, alert triage, SIEM concepts."),
      s("ir", "Incident response", "Containment, eradication, recovery, lessons learned."),
      s("labs", "Legal practice labs", "Only practise on labs and systems you are authorised to use."),
    ],
    advanced: ["Threat hunting", "Cloud security", "Application security", "Digital forensics", "Security architecture"],
    projects: [
      { level: "beginner", title: "Home lab", brief: "Virtual machines with logging to practise detection safely." },
      { level: "intermediate", title: "Secure-by-default web app", brief: "Fix OWASP issues in a deliberately vulnerable training app." },
      { level: "advanced", title: "Detection rules", brief: "Write and test detection rules against recorded lab activity." },
    ],
    interviewTopics: ["Networking basics", "Common attacks and defences", "Incident walkthrough", "Encryption vs hashing", "Least privilege"],
    resumeTips: ["List labs and write-ups; be precise about your role.", "Include certifications only if you actually hold them."],
    resources: [
      { title: "OWASP", url: "https://owasp.org/" },
      { title: "NIST Cybersecurity Framework", url: "https://www.nist.gov/cyberframework" },
    ],
    related: ["cloud-engineer", "software-engineer"],
  },
  {
    slug: "cloud-engineer",
    title: "Cloud Engineer",
    category: "Cloud",
    entry: "either",
    summary: "Build and run the infrastructure that modern applications live on.",
    overview:
      "Cloud engineers design, automate and operate infrastructure on platforms like AWS, Azure and Google Cloud. The role centres on reliability, security and cost — and on automating everything so it's repeatable.",
    education: ["Computing degrees are common; vendor certifications are widely recognised.", "Sysadmin and developer backgrounds both transition well."],
    skills: ["Linux", "Networking", "One cloud platform in depth", "Infrastructure as code", "Containers", "CI/CD", "Monitoring", "Security & IAM"],
    tools: ["AWS / Azure / Google Cloud", "Terraform", "Docker", "Kubernetes", "GitHub Actions", "Prometheus / Grafana"],
    responsibilities: ["Provision infrastructure as code", "Build deployment pipelines", "Monitor and respond to incidents", "Optimise cost", "Enforce security policies"],
    roadmap: [
      s("linux", "Linux", "Shell, processes, permissions, systemd."),
      s("net", "Networking", "VPCs, subnets, DNS, load balancers."),
      s("cloud", "A cloud platform", "Compute, storage, databases, IAM."),
      s("iac", "Infrastructure as code", "Terraform modules, state, environments."),
      s("containers", "Containers", "Docker images, registries, Kubernetes basics."),
      s("cicd", "CI/CD", "Automated build, test, deploy pipelines."),
      s("obs", "Observability", "Metrics, logs, traces, alerting."),
    ],
    advanced: ["Kubernetes operations", "Multi-region architecture", "FinOps", "Platform engineering", "Site reliability engineering"],
    projects: [
      { level: "beginner", title: "Static site with CI/CD", brief: "Automated deploy to object storage + CDN." },
      { level: "intermediate", title: "Terraform'd web stack", brief: "App, database and monitoring defined as code." },
      { level: "advanced", title: "Kubernetes platform", brief: "Cluster with GitOps, autoscaling and observability." },
    ],
    interviewTopics: ["Designing a highly available service", "IAM & least privilege", "Debugging an outage", "Terraform state", "Container networking"],
    resumeTips: ["Quantify reliability or cost improvements you measured.", "Name the exact services you operated."],
    resources: [
      { title: "AWS Skill Builder", url: "https://skillbuilder.aws/" },
      { title: "Microsoft Learn", url: "https://learn.microsoft.com/training/" },
      { title: "Google Cloud Skills Boost", url: "https://www.cloudskillsboost.google/" },
    ],
    related: ["software-engineer", "cybersecurity-analyst"],
  },
  {
    slug: "product-manager",
    title: "Product Manager",
    category: "Product",
    entry: "either",
    summary: "Decide what to build and why, and align people to ship it well.",
    overview:
      "Product managers own the problem: they understand users and the business, prioritise ruthlessly, and work with engineering and design to deliver outcomes. They lead through clarity and trust rather than authority.",
    education: ["No single required degree; engineering, business and design backgrounds are all common.", "Many PMs move in from engineering, analytics, design or operations roles."],
    skills: ["User research", "Prioritisation", "Writing clear specs", "Metrics & analytics", "Stakeholder communication", "Basic technical literacy", "Business models"],
    tools: ["Product analytics tools", "Figma", "Jira / Linear", "Notion / docs", "SQL (helpful)"],
    responsibilities: ["Define problems and success metrics", "Prioritise the roadmap", "Write product requirements", "Work with design & engineering", "Launch and measure"],
    roadmap: [
      s("users", "Understand users", "Interviews, jobs-to-be-done, problem statements."),
      s("metrics", "Metrics", "North-star metrics, funnels, retention."),
      s("prioritise", "Prioritisation", "Impact vs effort, trade-off frameworks."),
      s("specs", "Writing specs", "Clear PRDs, acceptance criteria."),
      s("tech", "Technical literacy", "APIs, databases, how software is shipped."),
      s("launch", "Launch & iterate", "Rollouts, experiments, feedback loops."),
      s("portfolio", "Product case studies", "Two written case studies of real or self-initiated products."),
    ],
    advanced: ["Product strategy", "Pricing", "Platform products", "Leading PM teams"],
    projects: [
      { level: "beginner", title: "Teardown of a product you use", brief: "Users, problems, metrics, one improvement with reasoning." },
      { level: "intermediate", title: "Ship a small product", brief: "Build or no-code an MVP, get real users, report results honestly." },
      { level: "advanced", title: "Growth experiment", brief: "Design, run and analyse an experiment on a live product." },
    ],
    interviewTopics: ["Product sense", "Metrics & estimation", "Prioritisation", "Execution & trade-offs", "Behavioural leadership"],
    resumeTips: ["Frame bullets as problem → action → measured outcome.", "Show cross-functional leadership with specifics."],
    resources: [{ title: "Lenny's Newsletter (free posts)", url: "https://www.lennysnewsletter.com/" }],
    related: ["ux-designer", "business-analyst", "startup-founder"],
  },
  {
    slug: "ux-designer",
    title: "UX / Product Designer",
    category: "Design",
    entry: "skills",
    summary: "Shape how products work and feel, from research to polished interfaces.",
    overview:
      "Product designers research user needs, map flows, prototype, and craft interfaces that are clear, accessible and consistent. They defend the user in every decision and work closely with product and engineering.",
    education: ["Design, HCI or psychology degrees are common; strong portfolios open doors on their own."],
    skills: ["User research", "Information architecture", "Interaction design", "Visual design & typography", "Prototyping", "Accessibility", "Design systems"],
    tools: ["Figma", "FigJam or Miro", "Prototyping tools", "Usability testing tools"],
    responsibilities: ["Run research and usability tests", "Design flows and interfaces", "Maintain design systems", "Collaborate on implementation"],
    roadmap: [
      s("principles", "Design principles", "Hierarchy, contrast, spacing, typography."),
      s("research", "User research", "Interviews, synthesis, personas used carefully."),
      s("ia", "Information architecture", "Navigation, content structure, flows."),
      s("interaction", "Interaction design", "States, feedback, error handling."),
      s("figma", "Figma", "Auto layout, components, variables, prototyping."),
      s("a11y", "Accessibility", "Contrast, focus, screen readers."),
      s("portfolio", "Portfolio", "Three case studies showing process and outcomes."),
    ],
    advanced: ["Design systems leadership", "Service design", "Design strategy", "Motion design"],
    projects: [
      { level: "beginner", title: "Redesign a local service's booking flow", brief: "Research, flows, before/after." },
      { level: "intermediate", title: "Mobile app end to end", brief: "Research to high-fidelity prototype with usability tests." },
      { level: "advanced", title: "Mini design system", brief: "Tokens, components, documentation, accessibility notes." },
    ],
    interviewTopics: ["Portfolio walkthrough", "Design critique", "Whiteboard challenge", "Research methods", "Working with engineers"],
    resumeTips: ["Link your portfolio first.", "Describe your role on team projects precisely."],
    resources: [
      { title: "Nielsen Norman Group articles", url: "https://www.nngroup.com/articles/" },
      { title: "WCAG overview (W3C)", url: "https://www.w3.org/WAI/standards-guidelines/wcag/" },
    ],
    related: ["frontend-developer", "product-manager", "graphic-designer"],
  },
  {
    slug: "financial-analyst",
    title: "Financial Analyst",
    category: "Finance",
    entry: "degree",
    summary: "Analyse financial data to guide investment, budgeting and business decisions.",
    overview:
      "Financial analysts build models, study company and market performance, and recommend actions. Precision, scepticism and clear writing matter as much as spreadsheet skill.",
    education: ["Degrees in finance, accounting, economics or commerce are typical.", "Professional designations are respected in many countries — check which apply where you want to work."],
    skills: ["Accounting fundamentals", "Financial statement analysis", "Excel modelling", "Valuation", "Corporate finance", "Communication"],
    tools: ["Excel", "Financial data terminals", "PowerPoint", "SQL / Python (increasingly)"],
    responsibilities: ["Build financial models", "Prepare forecasts and budgets", "Analyse performance", "Write reports and recommendations"],
    roadmap: [
      s("accounting", "Accounting", "Income statement, balance sheet, cash flow."),
      s("excel", "Excel modelling", "Formulas, scenarios, clean model structure."),
      s("analysis", "Statement analysis", "Ratios, trends, quality of earnings."),
      s("valuation", "Valuation", "DCF, comparables, their limitations."),
      s("markets", "Markets & economics", "Rates, inflation, how markets price risk."),
      s("comms", "Communicating", "Investment memos and presentations."),
    ],
    advanced: ["M&A modelling", "Risk management", "Portfolio management", "Quantitative finance"],
    projects: [
      { level: "beginner", title: "Personal budget model", brief: "Monthly model with scenarios." },
      { level: "intermediate", title: "Public company analysis", brief: "Three-statement model and written view." },
      { level: "advanced", title: "Valuation memo", brief: "DCF + comparables with stated assumptions and risks." },
    ],
    interviewTopics: ["Walk through the three statements", "DCF basics", "Market sizing", "A company you follow"],
    resumeTips: ["Specify the models and analyses you built.", "Only list designations you hold or are formally enrolled in."],
    resources: [{ title: "Khan Academy: Finance & capital markets", url: "https://www.khanacademy.org/economics-finance-domain/core-finance" }],
    related: ["data-analyst", "business-analyst"],
  },
  {
    slug: "nurse",
    title: "Registered Nurse",
    category: "Healthcare",
    entry: "degree",
    summary: "Provide and coordinate patient care, education and support.",
    overview:
      "Nurses assess patients, give treatments and medications, educate families, and coordinate care across teams. Licensing rules differ by country, so always check the regulator where you plan to practise.",
    education: ["A nursing diploma or degree plus a national licensing exam is required in most countries.", "Requirements for working abroad vary — check the destination country's nursing regulator."],
    skills: ["Clinical assessment", "Patient communication", "Medication safety", "Teamwork", "Documentation", "Resilience"],
    tools: ["Electronic health records", "Clinical monitoring equipment"],
    responsibilities: ["Assess and monitor patients", "Administer care and medications", "Educate patients and families", "Coordinate with doctors and allied health"],
    roadmap: [
      s("science", "Science foundations", "Biology, chemistry, anatomy and physiology."),
      s("program", "Nursing programme", "Accredited diploma or degree in your country."),
      s("clinical", "Clinical placements", "Supervised practice across specialities."),
      s("license", "Licensing exam", "Your country's nursing licence."),
      s("specialise", "Specialise", "Critical care, paediatrics, community health and more."),
    ],
    advanced: ["Nurse practitioner roles (where available)", "Nursing leadership", "Nurse education", "Research"],
    projects: [{ level: "beginner", title: "Anatomy revision flashcards", brief: "Build and practise a spaced-repetition deck." }],
    interviewTopics: ["Patient safety scenarios", "Communication with families", "Teamwork under pressure", "Ethics"],
    resumeTips: ["List placements with settings and responsibilities.", "Include licence details exactly as issued."],
    resources: [{ title: "World Health Organization: Nursing", url: "https://www.who.int/health-topics/nursing" }],
    related: ["doctor"],
  },
  {
    slug: "doctor",
    title: "Doctor (Physician)",
    category: "Medicine",
    entry: "degree",
    summary: "Diagnose and treat illness, and help people stay well.",
    overview:
      "Doctors combine deep medical knowledge with judgement and communication. The path is long and regulated: medical school, licensing, then often years of specialist training. Entrance exams and routes differ by country.",
    education: ["A medical degree (e.g. MBBS, MD) followed by licensing and, usually, residency or specialist training.", "Entrance exams differ by country (for example NEET in India)."],
    skills: ["Biology, chemistry & physics foundations", "Clinical reasoning", "Communication & empathy", "Ethics", "Lifelong learning"],
    tools: ["Clinical guidelines", "Electronic health records", "Diagnostic equipment"],
    responsibilities: ["Take histories and examine patients", "Order and interpret investigations", "Diagnose and manage conditions", "Counsel patients and families"],
    roadmap: [
      s("school", "School science", "Strong biology, chemistry and physics foundations."),
      s("entrance", "Entrance exam", "Prepare for your country's medical entrance exam."),
      s("medschool", "Medical school", "Pre-clinical and clinical years."),
      s("license", "Licensing & internship", "National licensing requirements."),
      s("residency", "Specialist training", "Residency or equivalent in your chosen field."),
    ],
    advanced: ["Sub-specialisation", "Research", "Public health", "Medical education"],
    projects: [{ level: "beginner", title: "Structured revision plan", brief: "A weekly plan with spaced repetition for entrance-exam subjects." }],
    interviewTopics: ["Why medicine?", "Ethical scenarios", "Teamwork and resilience"],
    resumeTips: ["Highlight research, volunteering and clinical exposure honestly."],
    resources: [{ title: "World Health Organization", url: "https://www.who.int/" }],
    related: ["nurse", "research-scientist"],
  },
  {
    slug: "lawyer",
    title: "Lawyer",
    category: "Law",
    entry: "degree",
    summary: "Advise clients, draft agreements and represent people and organisations.",
    overview:
      "Lawyers interpret the law and apply it to real problems — contracts, disputes, compliance, rights. Admission rules are jurisdiction-specific, so the route depends heavily on where you want to practise.",
    education: ["A law degree plus admission to the bar or equivalent in your jurisdiction.", "Some countries use an entrance exam for law school (for example CLAT in India, LSAT in the US)."],
    skills: ["Legal research", "Analytical reasoning", "Drafting", "Negotiation", "Advocacy", "Ethics"],
    tools: ["Legal research databases", "Document management systems"],
    responsibilities: ["Research legal questions", "Draft and review documents", "Advise clients", "Negotiate and represent"],
    roadmap: [
      s("reading", "Reading & reasoning", "Critical reading, logical argument."),
      s("entrance", "Entrance (if applicable)", "Your jurisdiction's law school entrance test."),
      s("degree", "Law degree", "Core subjects: contract, tort, constitutional, criminal law."),
      s("moot", "Moots & internships", "Practical advocacy and chambers/firm experience."),
      s("admission", "Admission to practise", "Bar exam or equivalent."),
    ],
    advanced: ["Corporate & commercial law", "Technology & data protection law", "International arbitration", "Policy work"],
    projects: [{ level: "beginner", title: "Case brief portfolio", brief: "Summarise five landmark cases in plain language." }],
    interviewTopics: ["Why law?", "A case you find interesting", "Ethical dilemmas", "Drafting exercise"],
    resumeTips: ["List moots, internships and publications with your specific contribution."],
    resources: [{ title: "Legal Information Institute (Cornell)", url: "https://www.law.cornell.edu/" }],
    related: ["civil-services-officer", "business-analyst"],
  },
  {
    slug: "business-analyst",
    title: "Business Analyst",
    category: "Business",
    entry: "either",
    summary: "Bridge business needs and technology by turning problems into clear requirements.",
    overview:
      "Business analysts study how an organisation works, find problems worth solving, and define requirements that teams can build. It suits people who enjoy both people and structured thinking.",
    education: ["Business, economics, IT or engineering degrees are common."],
    skills: ["Requirements gathering", "Process mapping", "Data analysis", "Stakeholder management", "Writing", "SQL basics"],
    tools: ["Spreadsheets", "Process modelling tools", "Jira", "SQL", "BI tools"],
    responsibilities: ["Interview stakeholders", "Map current and future processes", "Write requirements", "Support testing and rollout"],
    roadmap: [
      s("process", "Process thinking", "Flowcharts, swimlanes, bottlenecks."),
      s("requirements", "Requirements", "User stories, acceptance criteria."),
      s("data", "Data skills", "Spreadsheets, SQL, dashboards."),
      s("comms", "Stakeholders", "Facilitation, presenting options."),
      s("domain", "Domain knowledge", "Learn one industry deeply."),
    ],
    advanced: ["Product ownership", "Enterprise architecture", "Change management"],
    projects: [{ level: "beginner", title: "Process improvement case", brief: "Map a real process, find waste, propose and cost a fix." }],
    interviewTopics: ["Requirements elicitation", "Conflicting stakeholders", "SQL basics", "Case study"],
    resumeTips: ["Show the business outcome of changes you specified."],
    resources: [{ title: "IIBA resources", url: "https://www.iiba.org/" }],
    related: ["product-manager", "data-analyst"],
  },
  {
    slug: "digital-marketer",
    title: "Digital Marketer",
    category: "Marketing",
    entry: "skills",
    summary: "Grow products and brands through content, search, social and paid channels.",
    overview:
      "Digital marketers find the right audience, craft messages, and measure what works. It's a blend of creativity and analytics, and it changes fast — so learning by running real campaigns matters.",
    education: ["Marketing or communications degrees help but results-based portfolios matter most."],
    skills: ["Copywriting", "SEO", "Content strategy", "Social media", "Paid acquisition", "Analytics", "Email marketing"],
    tools: ["Google Analytics", "Search Console", "Ad platforms", "Email platforms", "Canva / Figma"],
    responsibilities: ["Plan campaigns", "Create content", "Manage channels and budgets", "Measure and report results"],
    roadmap: [
      s("fundamentals", "Marketing fundamentals", "Positioning, audience, funnel."),
      s("copy", "Copywriting", "Headlines, landing pages, calls to action."),
      s("seo", "SEO", "Keyword research, on-page, technical basics."),
      s("social", "Social & content", "Content calendars, community."),
      s("paid", "Paid channels", "Targeting, budgets, creative testing."),
      s("analytics", "Analytics", "Attribution, conversion tracking, reporting."),
    ],
    advanced: ["Growth marketing", "Marketing automation", "Brand strategy"],
    projects: [{ level: "beginner", title: "Grow a niche blog or page", brief: "Publish consistently for 8 weeks and report honest metrics." }],
    interviewTopics: ["Campaign you ran", "Metrics you'd track", "Budget allocation", "SEO basics"],
    resumeTips: ["Report real, verifiable numbers — never estimates dressed up as results."],
    resources: [{ title: "Google Search Central", url: "https://developers.google.com/search/docs" }],
    related: ["sales-representative", "product-manager"],
  },
  {
    slug: "sales-representative",
    title: "Sales Development Representative",
    category: "Sales",
    entry: "skills",
    summary: "Start conversations with potential customers and qualify real opportunities.",
    overview:
      "SDRs research prospects, reach out, and qualify interest for account executives. It's a common entry point into sales and business careers that rewards resilience, listening and organisation.",
    education: ["No specific degree required; communication skills and persistence matter most."],
    skills: ["Prospecting", "Written & verbal communication", "Active listening", "Objection handling", "CRM hygiene", "Resilience"],
    tools: ["CRM (e.g. HubSpot, Salesforce)", "LinkedIn", "Email sequencing tools"],
    responsibilities: ["Research target accounts", "Run outreach", "Qualify leads", "Book meetings"],
    roadmap: [
      s("product", "Know the product", "Problems it solves and for whom."),
      s("prospect", "Prospecting", "Ideal customer profiles, research."),
      s("outreach", "Outreach", "Personalised email and calls."),
      s("discovery", "Discovery", "Questions that uncover real needs."),
      s("crm", "CRM discipline", "Accurate notes and pipeline."),
    ],
    advanced: ["Account executive", "Sales engineering", "Sales leadership"],
    projects: [{ level: "beginner", title: "Outreach practice", brief: "Write and role-play a personalised outreach sequence." }],
    interviewTopics: ["Mock cold call", "Handling rejection", "Why sales?"],
    resumeTips: ["Use verified quota attainment figures if you have them."],
    resources: [{ title: "HubSpot Academy", url: "https://academy.hubspot.com/" }],
    related: ["digital-marketer", "startup-founder"],
  },
  {
    slug: "research-scientist",
    title: "Research Scientist",
    category: "Research",
    entry: "degree",
    summary: "Generate new knowledge through careful experiments and analysis.",
    overview:
      "Research scientists ask open questions, design experiments, analyse results and publish. The path usually runs through postgraduate study, and intellectual honesty is non-negotiable.",
    education: ["A master's or PhD is typical for independent research roles."],
    skills: ["Scientific method", "Statistics", "Reading papers", "Scientific writing", "Programming for analysis", "Domain expertise"],
    tools: ["Python / R", "Reference managers", "LaTeX", "Lab or compute infrastructure"],
    responsibilities: ["Design and run experiments", "Analyse data", "Write papers", "Review others' work"],
    roadmap: [
      s("fundamentals", "Deep fundamentals", "Your field's core maths and theory."),
      s("papers", "Reading papers", "Summarise and critique papers weekly."),
      s("methods", "Research methods", "Experimental design, statistics, reproducibility."),
      s("undergrad", "Undergraduate research", "Assist a lab or professor."),
      s("grad", "Postgraduate study", "Master's or PhD programme."),
    ],
    advanced: ["Leading a research group", "Grant writing", "Industry research labs"],
    projects: [{ level: "intermediate", title: "Reproduce a paper", brief: "Re-implement a published result and report differences honestly." }],
    interviewTopics: ["Your research", "Methodology critique", "Technical depth in your field"],
    resumeTips: ["List publications exactly as cited; mark preprints clearly."],
    resources: [{ title: "arXiv", url: "https://arxiv.org/" }],
    related: ["ai-engineer", "doctor"],
  },
  {
    slug: "mechanical-engineer",
    title: "Mechanical Engineer",
    category: "Engineering",
    entry: "degree",
    summary: "Design and improve machines, products and energy systems.",
    overview:
      "Mechanical engineers apply physics and materials science to design everything from consumer products to engines and HVAC systems, balancing performance, safety, cost and manufacturability.",
    education: ["An accredited engineering degree; professional registration requirements vary by country."],
    skills: ["Mechanics & thermodynamics", "CAD", "Materials", "Manufacturing processes", "Simulation (FEA/CFD)", "Problem solving"],
    tools: ["SolidWorks / Fusion 360 / CATIA", "MATLAB", "Simulation tools"],
    responsibilities: ["Design components and systems", "Run analyses and tests", "Work with manufacturing", "Document designs"],
    roadmap: [
      s("maths", "Maths & physics", "Calculus, mechanics, thermodynamics."),
      s("cad", "CAD", "Parametric modelling, drawings, tolerances."),
      s("materials", "Materials & manufacturing", "Selection, processes, DFM."),
      s("sim", "Simulation", "FEA and CFD basics."),
      s("project", "Build something", "Design, fabricate and test a real part."),
    ],
    advanced: ["Robotics", "Electric vehicles", "Renewable energy systems", "Product development leadership"],
    projects: [{ level: "intermediate", title: "Design & print a mechanism", brief: "CAD, tolerance analysis, 3D-printed prototype, test log." }],
    interviewTopics: ["Engineering fundamentals", "A design you made", "Failure analysis"],
    resumeTips: ["Show designs with measurable performance targets you met."],
    resources: [{ title: "MIT OpenCourseWare: Mechanical Engineering", url: "https://ocw.mit.edu/search/?d=Mechanical%20Engineering" }],
    related: ["software-engineer", "research-scientist"],
  },
  {
    slug: "civil-services-officer",
    title: "Civil Services Officer",
    category: "Government",
    entry: "degree",
    summary: "Serve the public by shaping and delivering government policy and services.",
    overview:
      "Civil servants implement policy, administer public services and advise leaders. Entry routes and exams are country-specific (for example the UPSC Civil Services Examination in India).",
    education: ["Usually a bachelor's degree in any discipline, plus a competitive public-service exam in many countries."],
    skills: ["General studies & current affairs", "Essay writing", "Analytical reasoning", "Public administration", "Ethics & integrity", "Communication"],
    tools: ["Government reports", "Newspapers & policy analysis"],
    responsibilities: ["Administer public programmes", "Draft and implement policy", "Coordinate departments", "Serve citizens"],
    roadmap: [
      s("syllabus", "Understand the exam", "Syllabus, pattern and past papers for your country."),
      s("foundations", "Foundations", "History, geography, polity, economy."),
      s("current", "Current affairs", "Daily reading and notes."),
      s("writing", "Answer writing", "Structured essays and answers."),
      s("mocks", "Mock tests", "Timed practice with review."),
    ],
    advanced: ["Policy specialisation", "Public leadership"],
    projects: [{ level: "beginner", title: "Policy brief", brief: "Two-page brief on a local issue with options and trade-offs." }],
    interviewTopics: ["Personality & motivation", "Current affairs", "Ethical dilemmas", "Your home region"],
    resumeTips: ["Public-service applications usually have fixed formats — follow them exactly."],
    resources: [{ title: "UPSC (India)", url: "https://upsc.gov.in/" }],
    related: ["lawyer", "business-analyst"],
  },
  {
    slug: "startup-founder",
    title: "Startup Founder",
    category: "Entrepreneurship",
    entry: "skills",
    summary: "Find a real problem, build a solution people pay for, and grow a company.",
    overview:
      "Founders do whatever the company needs: talking to customers, building, selling, hiring and raising money. There's no required credential — evidence that customers want what you're building is what counts.",
    education: ["No required degree. Learning by building, selling and talking to customers is the core curriculum."],
    skills: ["Customer discovery", "Building an MVP", "Sales", "Financial basics", "Hiring", "Resilience & focus"],
    tools: ["No-code/low-code tools", "Analytics", "Payment providers", "CRM"],
    responsibilities: ["Validate problems", "Ship and iterate the product", "Sell to early customers", "Manage cash", "Build the team"],
    roadmap: [
      s("problem", "Find a problem", "Talk to 20+ potential customers before building."),
      s("mvp", "Build an MVP", "Smallest thing that tests the riskiest assumption."),
      s("sell", "Sell it", "Get your first paying customers."),
      s("metrics", "Measure", "Retention, revenue, unit economics."),
      s("iterate", "Iterate", "Double down on what works."),
    ],
    advanced: ["Fundraising", "Scaling teams", "International expansion"],
    projects: [{ level: "beginner", title: "Validation sprint", brief: "Interview 15 people, write up findings, decide go / pivot / stop." }],
    interviewTopics: ["Investor pitch", "Customer evidence", "Market sizing"],
    resumeTips: ["Describe what you built and learned honestly, including failures."],
    resources: [{ title: "Y Combinator Startup School", url: "https://www.startupschool.org/" }],
    related: ["product-manager", "sales-representative"],
  },
  {
    slug: "graphic-designer",
    title: "Graphic Designer",
    category: "Creative",
    entry: "skills",
    summary: "Communicate ideas visually through branding, layouts and illustration.",
    overview:
      "Graphic designers create logos, brand systems, marketing materials and digital graphics. Craft, taste and understanding the client's goal matter more than any single tool.",
    education: ["Design degrees help; a strong portfolio of original work is essential."],
    skills: ["Typography", "Colour theory", "Layout & grids", "Branding", "Illustration", "Client communication"],
    tools: ["Figma", "Adobe Illustrator / Photoshop / InDesign", "Affinity suite"],
    responsibilities: ["Interpret briefs", "Create concepts", "Produce final artwork", "Maintain brand consistency"],
    roadmap: [
      s("fundamentals", "Design fundamentals", "Composition, hierarchy, contrast."),
      s("type", "Typography", "Pairing, spacing, readability."),
      s("colour", "Colour", "Palettes, accessibility, meaning."),
      s("tools", "Tools", "Vector and raster editing."),
      s("brand", "Branding", "Logos and identity systems."),
      s("portfolio", "Portfolio", "Original projects with process shown."),
    ],
    advanced: ["Art direction", "Motion graphics", "Brand strategy"],
    projects: [{ level: "beginner", title: "Identity for a local business", brief: "Logo, palette, type, and three applications (with permission)." }],
    interviewTopics: ["Portfolio walkthrough", "Handling feedback", "Brief interpretation"],
    resumeTips: ["Portfolio link first; credit collaborators accurately."],
    resources: [{ title: "Google Fonts knowledge", url: "https://fonts.google.com/knowledge" }],
    related: ["ux-designer", "digital-marketer"],
  },
];

export function getCareer(slug: string) {
  return careers.find((c) => c.slug === slug);
}

export function careersByCategory() {
  return CAREER_CATEGORIES.map((category) => ({
    category,
    careers: careers.filter((c) => c.category === category),
  })).filter((g) => g.careers.length > 0);
}
